In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# Step 1: Import the required libraries

# Step 2: Define the auto-encoder model class with a bilinear layer
class AutoEncoder(nn.Module):
    def __init__(self):
        super(AutoEncoder, self).__init__()

        # Define the encoder layers
        self.encoder = nn.Sequential(
            nn.Linear(input_size1, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, latent_size)
        )

        # Define the bilinear layer
        self.bilinear = nn.Bilinear(latent_size, input_size2, bilinear_size)

        # Define the decoder layers
        self.decoder = nn.Sequential(
            nn.Linear(bilinear_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, input_size2)
        )

    def forward(self, x1, x2):
        # Forward pass through the encoder
        encoded = self.encoder(x1)

        # Apply the bilinear layer to the encoded representation and the second input
        bilinear = self.bilinear(encoded, x2)

        # Forward pass through the decoder
        decoded = self.decoder(bilinear)

        return decoded

# Step 3: Instantiate the auto-encoder model
model = AutoEncoder()

# Step 4: Define the loss functions for each input
loss_function1 = nn.MSELoss()
loss_function2 = nn.MSELoss()

# Step 5: Define the optimizer
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Step 6: Train the auto-encoder model
for epoch in range(num_epochs):
    # Clear gradients
    optimizer.zero_grad()

    # Forward pass
    outputs = model(input1, input2)

    # Calculate the losses for each input
    loss1 = loss_function1(outputs, input1)
    loss2 = loss_function2(outputs, input2)

    # Backward pass and optimization
    loss1.backward(retain_graph=True)
    loss2.backward()
    optimizer.step()

    # Print the loss for monitoring the training progress
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss1: {loss1.item()}, Loss2: {loss2.item()}")

In [9]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms

In [10]:
class Autoencoder(nn.Module):
    def __init__(self, input_dim, encoder_dims, decoder_dims, bilinear_output_dim):
        super(Autoencoder, self).__init__()

        # Encoder
        encoder_layers = []
        prev_dim = input_dim
        for dim in encoder_dims:
            encoder_layers.append(nn.Linear(prev_dim, dim))
            encoder_layers.append(nn.ReLU())
            prev_dim = dim
        self.encoder = nn.Sequential(*encoder_layers)

        # Bi-Linear Layer
        self.bilinear = nn.Bilinear(encoder_dims[-1], encoder_dims[-1], bilinear_output_dim)

        # Decoder
        decoder_layers = []
        prev_dim = bilinear_output_dim
        for dim in decoder_dims:
            decoder_layers.append(nn.Linear(prev_dim, dim))
            decoder_layers.append(nn.ReLU())
            prev_dim = dim
        decoder_layers.append(nn.Linear(prev_dim, input_dim))
        decoder_layers.append(nn.Sigmoid())
        self.decoder = nn.Sequential(*decoder_layers)

    def forward(self, features, labels):
        encoded_features = self.encoder(features)
        encoded_labels = self.encoder(labels)
        bi_linear_output = self.bilinear(encoded_features, encoded_labels)
        decoded_output = self.decoder(bi_linear_output)
        return decoded_output


In [11]:
# Load MNIST dataset
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

# train_dataset = datasets.MNIST(root='./data', train=True, transform=transform, download=True)
train_dataset = datasets.MNIST(root='./data', train=True, download=True)
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True)

In [12]:
# Example usage
input_dim = 784
encoder_dims = [256, 128, 64]
decoder_dims = [64, 128, 256]
bilinear_output_dim = 64

model = Autoencoder(input_dim, encoder_dims, decoder_dims, bilinear_output_dim)
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [20]:
# Training loop
for epoch in range(10):
    for batch_features, _ in train_loader:
        optimizer.zero_grad()
        batch_features = batch_features.view(batch_features.size(0), -1)
        batch_labels = torch.randn_like(batch_features)
        print(batch_labels)
        output = model(batch_features, batch_labels)
        loss = criterion(output, batch_features)
        loss.backward()
        optimizer.step()
    print(f"Epoch: {epoch+1}, Loss: {loss.item():.4f}")

tensor([[ 0.0093,  0.7901,  0.1266,  ..., -1.3399,  0.2120, -1.2520],
        [ 1.8342, -0.2249, -0.0246,  ..., -0.2261, -0.3390, -0.7169],
        [ 0.4607, -0.6347, -0.0690,  ...,  0.5388, -0.0795,  0.9916],
        ...,
        [ 0.2699, -0.4954, -0.3641,  ...,  1.4039, -0.4527, -0.6991],
        [ 1.2326,  1.9450, -0.2496,  ..., -0.0945, -0.6398,  0.4243],
        [ 0.6651, -0.1349,  1.3401,  ..., -0.6936,  0.5156,  0.5158]])
tensor([[-1.3803,  1.2431, -0.7309,  ..., -1.8558, -1.7864,  0.6134],
        [ 0.9163, -0.5690,  0.5937,  ...,  1.8671,  0.0724,  2.4347],
        [ 0.0387, -0.1458, -0.1976,  ...,  0.8817, -1.7894, -0.0113],
        ...,
        [ 0.8458, -0.4904, -0.5863,  ..., -0.6173,  0.7377, -0.8138],
        [-1.6920,  0.5212,  1.3509,  ...,  0.7744, -0.2332, -0.5998],
        [-0.2938, -0.2124, -0.3526,  ...,  0.9790,  0.8067, -1.6830]])
tensor([[-1.4597, -0.9908,  0.9593,  ...,  1.2737, -1.4040, -1.3606],
        [ 0.0522, -0.5830,  2.3903,  ...,  0.5487,  0.1456, -0

KeyboardInterrupt: 

In [18]:
test_dataset = datasets.MNIST(root='./data', train=False, download=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=10, shuffle=True)
import matplotlib.pyplot as plt

In [19]:
# Reconstruct and visualize samples
with torch.no_grad():
    for batch_features, _ in test_loader:
        batch_features = batch_features.view(batch_features.size(0), -1)
        batch_labels = torch.randn_like(batch_features)
        reconstructed = model(batch_features, batch_labels)

        # Visualize the original and reconstructed samples
        for i in range(batch_features.size(0)):
            original = batch_features[i].view(28, 28)
            reconstructed_img = reconstructed[i].view(28, 28)

            # Plot the images
            fig, axs = plt.subplots(1, 2)
            axs[0].imshow(original, cmap='gray')
            axs[0].set_title('Original')
            axs[0].axis('off')
            axs[1].imshow(reconstructed_img, cmap='gray')
            axs[1].set_title('Reconstructed')
            axs[1].axis('off')
            plt.show()

        break  # Break after visualizing one batch of samples

TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'PIL.Image.Image'>

In [ ]:
def forward(self, x1, x2):
        encoded1 = self.encoder(x1)
        encoded2 = self.encoder(x2)
        bilinear = self.bilinear(encoded1, encoded2)
        decoded = self.decoder(bilinear)
        return decoded